CREATE TABLE CONTACT (
) ;
ID INT NOT NULL АОТО INCREMENT
, FIRST_NAМE VARCHAR(60) NOT NULL
, LAST_NAМE VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION INT NOT NULL DEFAULT О
, UNIQUE UQ_CONTACT_l (FIRST_NAМE, LAST_NAМE)
, PRIМARY КЕУ (ID)
CREATE ТАВLЕ НОВВУ (
) ;
HOBBY_ID VARCНAR(20) NOT NULL
, PRIМARY КЕУ (HOBBY_ID)
CREATE TABLE CONTACT TEL DETAIL
ID INT NOT NOLL АОТО INCREМENT
) ;
, CONTACT ID INT NOT NULL
, TEL _ТУРЕ VARCHAR ( 2 О) NOT NULL
, TEL NUMBER VARCНAR ( 2 О) NOT NULL
, VERSION INT NOT NULL DEFAULT O
, UNIQUE UQ_CONTACT_TEL_DETAIL_l (CONTACT_ID, TEL_TYPE)
, PRIМARY КЕУ (ID)
, CONSTRAINT FK_CONTACT_TEL_DETAIL_l FOREIGN КЕУ (CONTACT_ID)
REFERENCES CONTACT (ID)